In [3]:
# Import libraries
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

In [7]:
#Load CSVs
file_path_2019 = Path("RESOURCES/2019.csv")
file_path_2018 = Path("RESOURCES/2018.csv")
file_path_2017 = Path("RESOURCES/2017.csv")
file_path_2016 = Path("RESOURCES/2016.csv")
file_path_2015 = Path("RESOURCES/2015.csv")
file_path_2014 = Path("RESOURCES/2014.csv")
file_path_2013 = Path("RESOURCES/2013.csv")
file_path_2012 = Path("RESOURCES/2012.csv")
file_path_2011 = Path("RESOURCES/2011.csv")
#Read in CSVs
df_2019 = pd.read_csv(file_path_2019)
df_2018 = pd.read_csv(file_path_2018)
df_2017 = pd.read_csv(file_path_2017)
df_2016 = pd.read_csv(file_path_2016)
df_2015 = pd.read_csv(file_path_2015)
df_2014 = pd.read_csv(file_path_2014)
df_2013 = pd.read_csv(file_path_2013)
df_2012 = pd.read_csv(file_path_2012)
df_2011 = pd.read_csv(file_path_2011)

In [17]:
#Concat Data
combined_epl_df = pd.concat([df_2019, df_2018, df_2017, df_2016, df_2015, df_2014, df_2013, df_2012, df_2011],axis="index", join="inner")
combined_epl_df.head()

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BWA,IWH,IWD,IWA,WHH,WHD,WHA,VCH,VCD,VCA
0,E0,09/08/2019,Liverpool,Norwich,4,1,H,4.0,0.0,H,...,18.50,1.15,8.00,18.00,1.12,8.5,21.00,1.14,9.5,23.00
1,E0,10/08/2019,West Ham,Man City,0,5,A,0.0,1.0,A,...,1.26,11.00,6.10,1.25,13.00,6.0,1.24,12.00,6.5,1.25
2,E0,10/08/2019,Bournemouth,Sheffield United,1,1,D,0.0,0.0,D,...,3.90,1.97,3.55,3.80,2.00,3.5,3.80,2.00,3.6,4.00
3,E0,10/08/2019,Burnley,Southampton,3,0,H,0.0,0.0,D,...,2.75,2.65,3.20,2.75,2.70,3.2,2.75,2.70,3.3,2.80
4,E0,10/08/2019,Crystal Palace,Everton,0,0,D,0.0,0.0,D,...,2.35,3.10,3.20,2.40,3.10,3.3,2.35,3.20,3.3,2.45

In [20]:
combined_epl_df['Date'].dtypes()

TypeError: 'numpy.dtype' object is not callable